image: Visual Studio 2022
build_script:
  - cmd: dotnet workload restore
  - cmd: dotnet restore
  - cmd: dotnet run --project src/Generator.Bind/Generator.Bind.csproj -c:Release
  - cmd: dotnet pack src/osuTK/osuTK.NS20.csproj -c:Release /p:Version=%APPVEYOR_BUILD_VERSION%
  - cmd: msbuild /t:pack src/osuTK.iOS/osuTK.iOS.csproj /p:Configuration=Release /p:Version=%APPVEYOR_BUILD_VERSION%
  - cmd: dotnet pack src/osuTK.Android/osuTK.Android.csproj -c:Release /p:Version=%APPVEYOR_BUILD_VERSION%
test: off
version: 1.0.{build}
artifacts:
  - path: 'src\osuTK\bin\Release\*.nupkg'
  - path: 'src\osuTK.iOS\bin\Release\*.nupkg'
  - path: 'src\osuTK.Android\bin\Release\*.nupkg'
